-- Run in Supabase: Dashboard → SQL Editor → New query → Run
-- Fixes PGRST205 "Could not find the table 'public.comments' in the schema cache"

CREATE TABLE IF NOT EXISTS public.comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    comment text,
    image_url text,
    likes integer DEFAULT 0,
    is_pinned boolean DEFAULT false,
    replies jsonb DEFAULT '[]'::jsonb,
    created_at timestamptz DEFAULT now(),
    liked_by_admin boolean DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_comments_created_at ON public.comments (created_at);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert comments" ON public.comments;
CREATE POLICY "Allow public insert comments"
ON public.comments FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read comments" ON public.comments;
CREATE POLICY "Allow public read comments"
ON public.comments FOR SELECT USING (true);
